[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  5

[OUTPUT]
    Name            es
    Match           *
    Host            elasticsearch
    Port            9200

    Logstash_Format On
    Logstash_Prefix docker-logs

    Suppress_Type_Name On

    Retry_Limit False